version: '2'
services:
    transactions_elasticsearch-app:
        image: transactions_elasticsearch
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://transactions_elasticsearch-postgresql:5432/transactions_elasticsearch
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=transactions_elasticsearch-elasticsearch:9300
        ports:
            - 8080:8080
    transactions_elasticsearch-postgresql:
        extends:
            file: postgresql.yml
            service: transactions_elasticsearch-postgresql
    transactions_elasticsearch-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: transactions_elasticsearch-elasticsearch
